import type { Metadata } from "next";
import localFont from "next/font/local";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Provider } from "@/providers/provider";
import Navbar from "@/components/shared/navbar";
import { cn } from "@/lib/utils";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const logoFont = localFont({
  src: "./fonts/logo-font.ttf",
  variable: "--font-logo",
  weight: "600",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          poppins.className,
          logoFont.variable,
          "dark:bg-black antialiased"
        )}
      >
        <Provider>
          <Navbar />
          <main className="relative h-full w-full">{children}</main>
        </Provider>
      </body>
    </html>
  );
}
